version: '3.4'

services:
    chatchat:
        image: chatchat
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgresql://user:password@example.com:port/dbname
            - NEXTAUTH_URL=http://localhost:3000
            - NEXTAUTH_SECRET=example
            - EMAIL_HOST=smtp.example.com
            - EMAIL_PORT=587
            - EMAIL_USERNAME=john@example.com
            - EMAIL_PASSWORD=example
            - EMAIL_FROM=John<john@example.com>
            #- GITHUB_CLIENT_ID=
            #- GITHUB_CLIENT_SECRET=
            #- GOOGLE_CLIENT_ID=
            #- GOOGLE_CLIENT_SECRET=
        ports:
            - 3000:3000
